# Generated by Django 3.2.5 on 2021-07-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_admin_user_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
    ]
