# Generated by Django 3.2.5 on 2021-07-25 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='External ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('CONSULTING', 'CONSULTING'), ('DIAGNOSIS', 'DIAGNOSIS'), ('REPAIR', 'REPAIR'), ('OTHER', 'OTHER')], max_length=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('READY', 'READY'), ('CLOSED', 'CLOSED')], max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
