# Generated by Django 3.2.5 on 2021-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='external_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.PositiveIntegerField(default='1', unique=True, verbose_name='External ID'),
            preserve_default=False,
        ),
    ]
