# Generated by Django 3.2.5 on 2021-07-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20210725_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
