# Generated by Django 3.2.5 on 2021-07-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20210724_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, choices=[('CONSULTING', 'CONSULTING'), ('DIAGNOSIS', 'DIAGNOSIS'), ('REPAIR', 'REPAIR'), ('RETURN', 'RETURN')], max_length=15, null=True),
        ),
    ]
