# Generated by Django 3.2.5 on 2021-07-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='text',
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
