# Generated by Django 3.2.5 on 2021-07-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, choices=[('CONSULTING', 'CONSULTING'), ('DIAGNOSIS', 'DIAGNOSIS'), ('REPAIR', 'REPAIR'), ('OTHER', 'OTHER')], max_length=15, null=True),
        ),
    ]
