# Generated by Django 3.2.5 on 2021-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_request_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, choices=[('CONSULTING', 'Consulting'), ('DIAGNOSIS', 'DIAGNOSIS'), ('REPAIR', 'REPAIR'), ('REPLACEMENT', 'REPLACEMENT'), ('RETURN', 'RETURN'), ('COMPLAINT', 'COMPLAINT'), ('OTHER', 'OTHER')], max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('SCHEDULED', 'SCHEDULED'), ('CANCELED', 'CANCELED'), ('CLOSED', 'CLOSED')], max_length=15),
        ),
    ]
