# Generated by Django 3.2.5 on 2021-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20210724_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('READY', 'READY'), ('CLOSED', 'CLOSED')], max_length=15, null=True),
        ),
    ]
