# Generated by Django 3.2.5 on 2021-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Consulting', 'Consulting'), ('Diagnosis', 'Diagnosis'), ('Repair', 'Repair'), ('Replacement', 'Replacement'), ('Return', 'Return'), ('Complaint', 'Complaint'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Closed', 'Closed')], max_length=15),
        ),
    ]
