# Generated by Django 3.2.5 on 2021-07-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
