# Generated by Django 3.2.5 on 2021-07-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20210722_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
